[build]
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/readings"
  to = "/.netlify/functions/readings"
  status = 200

[[redirects]]
  from = "/api/readings/*"
  to = "/.netlify/functions/readings"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200