services:
  - type: web
    name: mi-servidor-iot
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://admin:admin@cluster0.mongodb.net/iot-sensors
      - key: PORT
        value: 10000